//load in all custom images

#include <Weather_Icons/w01d.h> 
#include <Weather_Icons/w01n.h> 
#include <Weather_Icons/w02d.h> 
#include <Weather_Icons/w02n.h>  
#include <Weather_Icons/w03.h> 
#include <Weather_Icons/w04.h> 
#include <Weather_Icons/w09.h> 
#include <Weather_Icons/w10d.h> 
#include <Weather_Icons/w10n.h> 
#include <Weather_Icons/w11.h> 
#include <Weather_Icons/w13.h> 
#include <Weather_Icons/w50.h> 
#include <Weather_Icons/ws01d.h> 
#include <Weather_Icons/ws01n.h> 
#include <Weather_Icons/ws02d.h> 
#include <Weather_Icons/ws02n.h> 
#include <Weather_Icons/ws03.h> 
#include <Weather_Icons/ws04.h> 
#include <Weather_Icons/ws09.h> 
#include <Weather_Icons/ws10d.h> 
#include <Weather_Icons/ws10n.h> 
#include <Weather_Icons/ws11.h> 
#include <Weather_Icons/ws13.h> 
#include <Weather_Icons/ws50.h> 
#include <Weather_Icons/wt01d.h> 
#include <Weather_Icons/wt01n.h> 
#include <Weather_Icons/wt02d.h> 
#include <Weather_Icons/wt02n.h> 
#include <Weather_Icons/wt03.h> 
#include <Weather_Icons/wt04.h> 
#include <Weather_Icons/wt09.h> 
#include <Weather_Icons/wt10d.h> 
#include <Weather_Icons/wt10n.h> 
#include <Weather_Icons/wt11.h> 
#include <Weather_Icons/wt13.h> 
#include <Weather_Icons/wt50.h> 
#include <Weather_Icons/rain_small.h> 
#include <Weather_Icons/wind_large.h> 
#include <Weather_Icons/wind_small.h> 
#include <Weather_Icons/sunrise_small.h> 
#include <Weather_Icons/sunset_small.h> 
	